services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dbuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dbpass}
      POSTGRES_DB: ${POSTGRES_DB:-inventory}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dbuser} -d ${POSTGRES_DB:-inventory}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inventory-net
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://dbuser:dbpass@db:5432/inventory}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-True}
    networks:
      - inventory-net
    volumes:
      - ./src:/app/src 

networks:
  inventory-net:
    driver: bridge

volumes:
  postgres_data: